### ISSUE TITLE
Does not filter tests

### ISSUE THREAD

**Issue by gilesknap** [kondratyev-nv/vscode-python-test-adapter#102]
Thanks for a great extension. 

I'm finding that when I try to run a single test the entire suite is run. Only the test that I have launched gets the blue icon but it stays blue for ages while all the tests run.

An I doing something wrong?

Thanks.

**Comment by gilesknap** [comment]
My config looks like this:
{
    "python.pythonPath": "/scratch/hgv27681/cache/pipenv/test_malcolm-9VY5DVsh/bin/python",
    "python.testing.pytestArgs": [
        "tests"
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.nosetestsEnabled": false,
    "python.testing.pytestEnabled": true,
    "restructuredtext.confPath": "${workspaceFolder}/docs"
}

**Comment by kondratyev-nv** [comment]
@gilesknap Thank you for the issue! I see you're using pytest. Is the `tests` argument from `python.testing.pytestArgs` required in your case? It seems that a set of tests to run evaluates to `tests <some-specific-test-to-run>` because of this argument This is similar to running tests with command `python -m pytest tests <some-specific-test-to-run>` which will run all tests from `tests` folder. Anyway, I will consider handling such arguments from the extension.

**Comment by gilesknap** [comment]
Hi, thanks, I'll try without the 'tests' parameter. It is added by default when you use the configure python tests command since it asks which folder to browse for tests.

I imagine that not having it would slow things down when initially discovering tests but not break anything.

**Comment by kondratyev-nv** [comment]
@gilesknap I've just published a new version 0.3.13 with the fix regarding positional arguments for pytest. Such arguments can now be used as a filter for discovering and running tests. Please, update and let me know if the issue persists.

**Comment by gilesknap** [comment]
This fixed it for me. Many thanks.
