### ISSUE TITLE
Extension Does Not Uninstall Correctly

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [kondratyev-nv/vscode-python-test-adapter#151]
I uninstalled the extension to examine something with the original vscode testing, but the Test Explorer panel remains and is inoperative. Also the Test Explorer option in the output log remains.

**Comment by kondratyev-nv** [comment]
@Anti-Distinctlyminty Thank you for the issue! This extension consists of two parts - Python Test Explorer itself and its dependency [Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer). Test Explorer UI provides side panel and common functionality so it can be used by other test explorers (for example, to discover and run C++ tests). Unfortunately, because of that uninstalling Python Test Explorer won't remove Test Explorer UI from your VSCode. Test Explorer panel and Test Explorer log in the Output are provided by Test Explorer UI extension. If you don't have any other Test Explorers and want to remove the side panel, just remove Test Explorer UI extension.

**Comment by Anti-Distinctlyminty** [comment]
Thanks for the quick response!
