### ISSUE TITLE
Run py File in Debug Mode

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [kondratyev-nv/vscode-python-test-adapter#152]
I need to debug a test, but that test depends on the other tests being run, but I cannot start testing the whole py file in debug mode as there is not debug button, as you can see in this image

![image](https://user-images.githubusercontent.com/1378483/82312962-05eabc00-99c8-11ea-9246-9e92e74046f7.png)

**Comment by kondratyev-nv** [comment]
@Anti-Distinctlyminty Thank you for the issue! Can you please check if any of the extensions are not up-to-date? Also, what Python version and what test framework are you using? I'm asking this because it looks like this feature was implemented in Test Explorer UI a couple of days ago - https://github.com/hbenl/vscode-test-explorer/issues/138. And right now I can see debug button for my test suites
<img width="277" alt="image" src="https://user-images.githubusercontent.com/4085884/82331344-a94dc800-99ec-11ea-88b1-3038faab4bff.png">

**Comment by Anti-Distinctlyminty** [comment]
Ah, there was a 'reload required' waiting for me which had passed me by. Apologies for that.
However, when debugging I'm not hitting any break points, by clicking on the debug icon on the py file or the debug icon for the function.

Using pytest and Python 3.6.9 64-bit
(I'm simultaneously running a debug flask server if that matters)
