### ISSUE TITLE
Export junit report

### ISSUE THREAD

**Issue by timrid** [kondratyev-nv/vscode-python-test-adapter#172]
Is there a possibility to export a single junit report from all tests that have been run. Even if the tests were executed individually.

This would be a great help for tests that take a long time. Then you only have to repeat the failed tests, but still get a complete test report.

**Comment by kondratyev-nv** [comment]
@timrid Thank you for the issue! I can see there are two problems there.
1. Python Test Adapter writes junit report to a temporary file. So at the moment, there is no easy way to get that report.
2. Combining results of multiple test executions to a single junit report.

I can address the first problem so that a user can provide a path to a junit xml report in arguments, and extension would look at that file to get the results. Please tell me if this feature is required to you.

However, I believe the second problem is better to be addressed by pytest team or some kind of a pytest plugin. So please create an issue at https://github.com/pytest-dev/pytest repo or look for any similar plugins.

**Comment by timrid** [comment]
For me it would be a very helpful feature if the path for the junit reports could be specified.

The combining of the junit reports would be an optionally feature for me. I have found some scripts (which I have not yet tested) that address exactly that problem: 
- https://gist.github.com/astraw38/168b23eed298c36b0411
- https://gist.github.com/cgoldberg/4320815

**Comment by kondratyev-nv** [comment]
@timrid I've published a new version 0.4.6 with respecting `junitxml` option during test execution. You can now provide a custom path to generate a report in `python.testing.pytestArgs`. For example, 
```
{
    "python.testing.pytestArgs": ["--junitxml=results.xml"]
}
```
However, notice that a report would be generated using `xunit1` format (like setting `junit_family=xunit1` in pytest.ini).

**Comment by timrid** [comment]
Thanks a lot! That sounds like a good solution. I will test it in the next days.

**Comment by kondratyev-nv** [comment]
@timrid I’m closing this issue. If exporting junit report is not working for you, please feel free to reopen and comment.
