### ISSUE TITLE
Running Test Via Codelens Does not update the test status on the Test Explorer

### ISSUE THREAD

**Issue by angelitoTalens** [kondratyev-nv/vscode-python-test-adapter#234]
Steps:

Open the test file using "Show Source Button"
Run test using Codelens via "Run Test"

Result:
Test was executed successfully and updates the default Python unit test explorer but not this

**Comment by kondratyev-nv** [comment]
@angelitoTalens This is expected behavior. Python Test Explorer and Python extension share only settings to simplify configuration. They have different execution logic though. In general, there should be 2 sets of Codelenses - one from the Python Extension and one from this one. If this would be of help I can take a look at why there is no set of Codelenses from Python Test Explorer in your case.

**Comment by angelitoTalens** [comment]
Ok understand. I'm happy to close the issue then
