### ISSUE TITLE
UX suggestion: sort the groups alphabetically

### ISSUE THREAD

**Issue by darkvertex** [kondratyev-nv/vscode-python-test-adapter#31]
With a lot of multiple roots in a workspace, it can get a bit difficult to scroll considering it's not sorted alphabetically.

Would it be hard to add an alphabetic sort of the treeview items?

**Comment by kondratyev-nv** [comment]
Thank you for the suggestion! Are you talking about items on all levels or just roots?

**Comment by lsnodak** [comment]
For me the roots would be nice, but I think it would be a nice-to-have at both levels! Especially helpful when there are a lot of tests

**Comment by darkvertex** [comment]
I was thinking roots at the very least, but the option for both levels would be very welcome.

**Comment by kondratyev-nv** [comment]
@lsnodak @darkvertex Well, I am asking because folders appear in the order they are set in `<your-workspace>.code-workspace` file. For example, see https://github.com/kondratyev-nv/vscode-python-test-adapter/blob/master/test/test_samples/samples-workspace.code-workspace. If I open this workspace, the folders in Explorer will be in the same order they are defined in this file. I think this way is preferable instead of the alphabetic one, don't you?

Anyway, there is no sorting set for the tests in the Test view for the extension now. I'll have a look at sorting for at least test suites and test cases.

**Comment by kondratyev-nv** [comment]
@lsnodak @darkvertex I have published release 0.2.4. Alphabetic sorting was added there for test suites and test cases. Sorting top level for multiple workspaces seems to be handled from [Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer). Still, I had not found any case when top-level appeared not in order folders are defined in `.code-workspace` file. Please, update the extension and let me know if you have any issues with that approach.

**Comment by kondratyev-nv** [comment]
I'm closing this issue because this feature was released and it looks like there are no problems with that right now. If someone has any issues feel free to create a new one!
