### ISSUE TITLE
Python Test Explorer does not show test if Test Framework set to null

### ISSUE THREAD

**Issue by mrvkino** [kondratyev-nv/vscode-python-test-adapter#78]
If the Test framework is left to `null` the extension is not able to show the test even if the python extension settings are set to Unittest.

![image](https://user-images.githubusercontent.com/279511/56966069-6d6b6a80-6b2c-11e9-817f-a15476b73764.png)
![image](https://user-images.githubusercontent.com/279511/56966236-ac99bb80-6b2c-11e9-96aa-4ce7b9276d0a.png)
![image](https://user-images.githubusercontent.com/279511/56966331-e1a60e00-6b2c-11e9-9c0a-37e414a81775.png)

If I set Test Framework to Unittest the extension is able to show the tests in the side pane.
![image](https://user-images.githubusercontent.com/279511/56966373-f97d9200-6b2c-11e9-9f49-2ec568baa742.png)
![image](https://user-images.githubusercontent.com/279511/56966398-09957180-6b2d-11e9-8c1d-b63d4c653505.png)

I think this is happening because of the change in the settings of the Python extension settings name for the test framework option.

**Comment by kondratyev-nv** [comment]
Thank you for the issue! Indeed, from the description it looks like the problem is with the naming of the properties. Changes to config were introduced in https://github.com/Microsoft/vscode-python/issues/4999.
I probably will able to fix this only after May 7th, sorry if this cause you inconvenience.
